source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'social_engine', :git=>'git://github.com/charlotte-ruby/social_engine.git'

group :test do
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem "autotest-rails"
  gem "autotest-notification"
  gem "rspec"
  gem "rspec-rails"
  gem "spork"
  gem "launchy"
  gem "systemu"
end

